# Generated by Django 5.1.1 on 2024-09-29 15:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categoryrole',
            unique_together={('user', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='channelrole',
            unique_together={('user', 'channel')},
        ),
        migrations.AlterUniqueTogether(
            name='workspacerole',
            unique_together={('user', 'workspace')},
        ),
        migrations.AlterField(
            model_name='categoryrole',
            name='role',
            field=models.CharField(choices=[('category_admin', 'Category_Admin'), ('category_member', 'Category_Member')], default='category_member', max_length=20),
        ),
        migrations.AlterField(
            model_name='channelrole',
            name='role',
            field=models.CharField(choices=[('reviewer', 'Reviewer'), ('reviewee', 'Reviewee')], default='reviewer', max_length=20),
        ),
        migrations.AlterField(
            model_name='workspacerole',
            name='role',
            field=models.CharField(choices=[('workspace_admin', 'Workspace_Admin'), ('workspace_member', 'Workspace_Member')], default='workspace_member', max_length=20),
        ),
    ]
