# Generated by Django 5.1.1 on 2024-10-15 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_alter_assignment_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='sent',
            new_name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='team',
            name='points_earned',
        ),
        migrations.AddField(
            model_name='iteration',
            name='remarks',
            field=models.TextField(default='\x7fgreat just change this field'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(default='complete coding ninjas course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(null=True, upload_to='submissions/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.related.ForeignKey>'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_leader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EarnedPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_points', models.IntegerField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.assignment')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reviewee_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.team')),
            ],
        ),
    ]
