# Generated by Django 5.1.1 on 2024-10-26 21:55

import django.db.models.deletion
import workspaces.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_rename_sent_submission_submitted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='iteration',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'Ongoing'), ('incomplete', 'Incomplete')], default='incomplete', max_length=20),
        ),
        migrations.AlterField(
            model_name='iteration',
            name='reviewee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewee_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(null=True, upload_to=workspaces.utils.submissions_file_path),
        ),
    ]
