# Generated by Django 5.1.1 on 2024-12-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.URLField(null=True),
        ),
    ]
