# Generated by Django 5.1.1 on 2024-12-24 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_alter_submission_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteration',
            name='status',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_leader',
        ),
        migrations.CreateModel(
            name='AssignmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'Ongoing'), ('incomplete', 'Incomplete')], max_length=10)),
                ('earned_points', models.IntegerField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_status', to='workspaces.assignment')),
                ('reviewee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_status_as_reviewee', to=settings.AUTH_USER_MODEL)),
                ('reviewee_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_statuses', to='workspaces.team')),
            ],
        ),
        migrations.DeleteModel(
            name='EarnedPoint',
        ),
    ]
