# Generated by Django 5.1.1 on 2024-12-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_remove_message_group_chat_remove_reply_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
