# Generated by Django 5.1.1 on 2024-09-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_level',
            field=models.CharField(choices=[('workspace', 'Workspace'), ('category', 'Category'), ('channel', 'Channel')], default='channel', max_length=15),
        ),
    ]
